// See https://aka.ms/new-console-template for more information
using AdoNetExamples;

CommandBuilderCrudDemo.RunAutoGeneratedCommandsWithCustomRetrievingIdentityViaOutputInserted();

//await DataReaderExamples.ReadDataFromTableAsync();